// This file is auto-generated by @hey-api/openapi-ts

export type AdminCreateAgentRequest = {
    name: string;
    identity: string;
    pre_prompt: string;
};

export type AdminCreateArtifactRequest = {
    user_ids: Array<number>;
    group_ids: Array<number>;
    variable_name: string;
    content: string;
};

export type AdminCreateUserRequest = {
    full_name: string;
    email: string;
    group_id: number | null;
};

export type AdminDeleteAgentRequest = {
    agent_id: number;
};

export type AdminDeleteAgentsRequest = {
    ids: Array<number>;
};

export type AdminDeleteArtifactRequest = {
    artifact_id: number;
};

export type AdminDeleteArtifactsRequest = {
    ids: Array<number>;
};

export type AdminDeleteClientRequest = {
    id: number;
};

export type AdminDeleteClientsRequest = {
    ids: Array<number>;
};

export type AdminGetAgentRequest = {
    id: number;
};

export type AdminGetArtifactRequest = {
    id: number;
};

export type AdminGetClientChatsRequest = {
    user_id: number;
};

export type AdminGetClientRequest = {
    id: number;
};

export type AdminUpdateAgentRequest = {
    id: number;
    name: string;
    identity: string;
    pre_prompt: string;
};

export type AdminUpdateArtifactRequest = {
    id: number;
    user_ids: Array<number>;
    group_ids: Array<number>;
    variable_name: string;
    content: string;
};

export type AdminUpdateUserRequest = {
    id: number;
    full_name: string;
    email: string;
    group_id: number | null;
};

export type BodyLoginForAccessTokenApiAuthLoginPost = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type CreateGroupRequest = {
    name: string;
    agent_id: number;
};

export type DeleteChatsRequest = {
    ids: Array<number>;
};

export type DeleteGroupRequest = {
    group_id: number;
};

export type DeleteGroupsRequest = {
    ids: Array<number>;
};

export type GetChatRequest = {
    id: number;
};

export type GetGroupRequest = {
    id: number;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type UpdateActiveAgentRequest = {
    agent_id: number;
};

export type UpdateGroupRequest = {
    id: number;
    name: string;
    agent_id: number;
};

export type UserCreate = {
    full_name: string;
    email: string;
    password: string;
    user_type: string;
    organisation_id: number;
    group_id: number | null;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type LoginForAccessTokenData = {
    body: BodyLoginForAccessTokenApiAuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginForAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginForAccessTokenError = LoginForAccessTokenErrors[keyof LoginForAccessTokenErrors];

export type LoginForAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type ReadUsersMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUsersMeError = ReadUsersMeErrors[keyof ReadUsersMeErrors];

export type ReadUsersMeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/users/register';
};

export type CreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminCreateUserData = {
    body: AdminCreateUserRequest;
    path?: never;
    query?: never;
    url: '/api/users/create-user';
};

export type AdminCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminCreateUserError = AdminCreateUserErrors[keyof AdminCreateUserErrors];

export type AdminCreateUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminUpdateUserData = {
    body: AdminUpdateUserRequest;
    path?: never;
    query?: never;
    url: '/api/users/update-user';
};

export type AdminUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminUpdateUserError = AdminUpdateUserErrors[keyof AdminUpdateUserErrors];

export type AdminUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminGetClientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/get-clients';
};

export type AdminGetClientsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminGetClientsError = AdminGetClientsErrors[keyof AdminGetClientsErrors];

export type AdminGetClientsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminGetClientData = {
    body: AdminGetClientRequest;
    path?: never;
    query?: never;
    url: '/api/users/get-client';
};

export type AdminGetClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminGetClientError = AdminGetClientErrors[keyof AdminGetClientErrors];

export type AdminGetClientResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminDeleteClientData = {
    body: AdminDeleteClientRequest;
    path?: never;
    query?: never;
    url: '/api/users/delete-client';
};

export type AdminDeleteClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminDeleteClientError = AdminDeleteClientErrors[keyof AdminDeleteClientErrors];

export type AdminDeleteClientResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminDeleteClientsData = {
    body: AdminDeleteClientsRequest;
    path?: never;
    query?: never;
    url: '/api/users/delete-clients';
};

export type AdminDeleteClientsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminDeleteClientsError = AdminDeleteClientsErrors[keyof AdminDeleteClientsErrors];

export type AdminDeleteClientsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminCreateArtifactData = {
    body: AdminCreateArtifactRequest;
    path?: never;
    query?: never;
    url: '/api/artifacts/create-artifact';
};

export type AdminCreateArtifactErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminCreateArtifactError = AdminCreateArtifactErrors[keyof AdminCreateArtifactErrors];

export type AdminCreateArtifactResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminUpdateArtifactData = {
    body: AdminUpdateArtifactRequest;
    path?: never;
    query?: never;
    url: '/api/artifacts/update-artifact';
};

export type AdminUpdateArtifactErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminUpdateArtifactError = AdminUpdateArtifactErrors[keyof AdminUpdateArtifactErrors];

export type AdminUpdateArtifactResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminGetArtifactData = {
    body: AdminGetArtifactRequest;
    path?: never;
    query?: never;
    url: '/api/artifacts/get-artifact';
};

export type AdminGetArtifactErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminGetArtifactError = AdminGetArtifactErrors[keyof AdminGetArtifactErrors];

export type AdminGetArtifactResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminDeleteArtifactData = {
    body: AdminDeleteArtifactRequest;
    path?: never;
    query?: never;
    url: '/api/artifacts/delete-artifact';
};

export type AdminDeleteArtifactErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminDeleteArtifactError = AdminDeleteArtifactErrors[keyof AdminDeleteArtifactErrors];

export type AdminDeleteArtifactResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminDeleteArtifactsData = {
    body: AdminDeleteArtifactsRequest;
    path?: never;
    query?: never;
    url: '/api/artifacts/delete-artifacts';
};

export type AdminDeleteArtifactsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminDeleteArtifactsError = AdminDeleteArtifactsErrors[keyof AdminDeleteArtifactsErrors];

export type AdminDeleteArtifactsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminGetArtifactsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/artifacts/get-artifacts';
};

export type AdminGetArtifactsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminGetArtifactsError = AdminGetArtifactsErrors[keyof AdminGetArtifactsErrors];

export type AdminGetArtifactsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetChatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chat/get-chats';
};

export type GetChatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChatsError = GetChatsErrors[keyof GetChatsErrors];

export type GetChatsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteChatsData = {
    body: DeleteChatsRequest;
    path?: never;
    query?: never;
    url: '/api/chat/delete-chats';
};

export type DeleteChatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteChatsError = DeleteChatsErrors[keyof DeleteChatsErrors];

export type DeleteChatsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetChatData = {
    body: GetChatRequest;
    path?: never;
    query?: never;
    url: '/api/chat/get-chat';
};

export type GetChatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChatError = GetChatErrors[keyof GetChatErrors];

export type GetChatResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminGetClientChatsData = {
    body: AdminGetClientChatsRequest;
    path?: never;
    query?: never;
    url: '/api/chat/admin-get-client-chats';
};

export type AdminGetClientChatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminGetClientChatsError = AdminGetClientChatsErrors[keyof AdminGetClientChatsErrors];

export type AdminGetClientChatsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminGetClientChatData = {
    body: GetChatRequest;
    path?: never;
    query?: never;
    url: '/api/chat/admin-get-client-chat';
};

export type AdminGetClientChatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminGetClientChatError = AdminGetClientChatErrors[keyof AdminGetClientChatErrors];

export type AdminGetClientChatResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientChatDocsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chat/ws/chat-docs';
};

export type ClientChatDocsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminChatDocsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chat/ws/admin-chat-docs';
};

export type AdminChatDocsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminCreateAgentData = {
    body: AdminCreateAgentRequest;
    path?: never;
    query?: never;
    url: '/api/agents/create-agent';
};

export type AdminCreateAgentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminCreateAgentError = AdminCreateAgentErrors[keyof AdminCreateAgentErrors];

export type AdminCreateAgentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminUpdateAgentData = {
    body: AdminUpdateAgentRequest;
    path?: never;
    query?: never;
    url: '/api/agents/update-agent';
};

export type AdminUpdateAgentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminUpdateAgentError = AdminUpdateAgentErrors[keyof AdminUpdateAgentErrors];

export type AdminUpdateAgentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminGetAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agents/get-agents';
};

export type AdminGetAgentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminGetAgentsError = AdminGetAgentsErrors[keyof AdminGetAgentsErrors];

export type AdminGetAgentsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminGetAgentData = {
    body: AdminGetAgentRequest;
    path?: never;
    query?: never;
    url: '/api/agents/get-agent';
};

export type AdminGetAgentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminGetAgentError = AdminGetAgentErrors[keyof AdminGetAgentErrors];

export type AdminGetAgentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminDeleteAgentData = {
    body: AdminDeleteAgentRequest;
    path?: never;
    query?: never;
    url: '/api/agents/delete-agent';
};

export type AdminDeleteAgentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminDeleteAgentError = AdminDeleteAgentErrors[keyof AdminDeleteAgentErrors];

export type AdminDeleteAgentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminDeleteAgentsData = {
    body: AdminDeleteAgentsRequest;
    path?: never;
    query?: never;
    url: '/api/agents/delete-agents';
};

export type AdminDeleteAgentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminDeleteAgentsError = AdminDeleteAgentsErrors[keyof AdminDeleteAgentsErrors];

export type AdminDeleteAgentsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminUpdateActiveAgentData = {
    body: UpdateActiveAgentRequest;
    path?: never;
    query?: never;
    url: '/api/organisation/update_active_agent';
};

export type AdminUpdateActiveAgentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminUpdateActiveAgentError = AdminUpdateActiveAgentErrors[keyof AdminUpdateActiveAgentErrors];

export type AdminUpdateActiveAgentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminGetActiveAgentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/organisation/get_active_agent';
};

export type AdminGetActiveAgentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminGetActiveAgentError = AdminGetActiveAgentErrors[keyof AdminGetActiveAgentErrors];

export type AdminGetActiveAgentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminCreateGroupData = {
    body: CreateGroupRequest;
    path?: never;
    query?: never;
    url: '/api/groups/create_group';
};

export type AdminCreateGroupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminCreateGroupError = AdminCreateGroupErrors[keyof AdminCreateGroupErrors];

export type AdminCreateGroupResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminUpdateGroupData = {
    body: UpdateGroupRequest;
    path?: never;
    query?: never;
    url: '/api/groups/update_group';
};

export type AdminUpdateGroupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminUpdateGroupError = AdminUpdateGroupErrors[keyof AdminUpdateGroupErrors];

export type AdminUpdateGroupResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminGetGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/groups/get_groups';
};

export type AdminGetGroupsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminGetGroupsError = AdminGetGroupsErrors[keyof AdminGetGroupsErrors];

export type AdminGetGroupsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminGetGroupData = {
    body: GetGroupRequest;
    path?: never;
    query?: never;
    url: '/api/groups/get_group';
};

export type AdminGetGroupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminGetGroupError = AdminGetGroupErrors[keyof AdminGetGroupErrors];

export type AdminGetGroupResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminDeleteGroupData = {
    body: DeleteGroupRequest;
    path?: never;
    query?: never;
    url: '/api/groups/delete_group';
};

export type AdminDeleteGroupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminDeleteGroupError = AdminDeleteGroupErrors[keyof AdminDeleteGroupErrors];

export type AdminDeleteGroupResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminDeleteGroupsData = {
    body: DeleteGroupsRequest;
    path?: never;
    query?: never;
    url: '/api/groups/delete_groups';
};

export type AdminDeleteGroupsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminDeleteGroupsError = AdminDeleteGroupsErrors[keyof AdminDeleteGroupsErrors];

export type AdminDeleteGroupsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ServeSpaData = {
    body?: never;
    path: {
        full_path: string;
    };
    query?: never;
    url: '/{full_path}';
};

export type ServeSpaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ServeSpaError = ServeSpaErrors[keyof ServeSpaErrors];

export type ServeSpaResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};